# Generated by Django 4.0.5 on 2022-06-24 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_alter_country_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0001_initial'),
        ('gallery', '0002_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
                ('region_url', models.CharField(max_length=255)),
                ('region_meta_keywords', models.CharField(max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region_images', models.ManyToManyField(db_table='region_images', related_name='region_images', to='gallery.image')),
            ],
            options={
                'db_table': 'region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContentRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
                ('region_info', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region')),
            ],
            options={
                'db_table': 'content_region',
                'ordering': ['id'],
            },
        ),
    ]
