# Generated by Django 4.0.5 on 2022-07-05 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('gallery', '0004_categoryimage_image_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='category_name',
        ),
        migrations.CreateModel(
            name='ContentCategoryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.language')),
            ],
        ),
    ]
